name: Auto Merge Predev

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_AUTO_MERGE }}

      - name: Setup Git Config
        run: |
          git config user.name "yhsdaniel"
          git config user.email "daniel.kristi09@github.com"

      - name: Fetch All Branches
        run: git fetch origin

      - name: Merge to main
        run: |
          git checkout main
          git fetch origin main
          git merge development
          git add .
          git commit -m "update (auto-merge)"
          git push origin main
        